url: "https://www.dotenv.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Dotenv" # the name of your site, e.g. ACME Corp.
logo: "https://raw.githubusercontent.com/motdotla/dotenv/master/dotenv.svg"
description: "Simplify your secrets"

# Footer "Edit this page on GitHub" link text
github_edit_link: true # show or hide edit this page link
github_edit_link_text: "View on GitHub"
github_edit_repository: "https://github.com/dotenv-org/dotenv-org.github.io" # the github URL for your repo
github_edit_branch: "master" # the branch that your docs is served from
github_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# For SEO Jekyll Plugin
author:
  name: Dotenv
  twitter: dotenvorg
twitter:
  username: dotenvorg
  card: summary
social:
  name: Dotenv
  links:
    - https://twitter.com/dotenvorg
    - https://github.com/dotenv-org
    - https://linkedin.com/company/dotenvorg
    - https://www.youtube.com/@dotenvorg

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/default-cover-image.png"
      # image: "https://res.cloudinary.com/dotenv-org/image/upload/v1666566686/og-image_g0llrh.png"

# For Favicon Plugin
favicon:
  source: "favicon.png"

# Exclude files
exclude:
  - .DS_Store
  - README.md

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-redirect-from
  - liquid_pluralize
  - liquid_reading_time
  - jekyll-timeago
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-favicon
  - jekyll-feed
  - jemoji
  - jekyll-gzip
  - jekyll-loading-lazy
  - jekyll-responsive-image

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html #THIS ONE
# [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90
# [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
# [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false
# [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: true
# [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: uploads
# [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}
# [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false
# [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false
# [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - uploads/*/*/*/*.{jpeg,jpg}
